export default function Head() {
  return (
    <>
      <title>Song Liansheng's Site</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
