create table notes (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  description text
);

create table comments (
  id bigint generated by default as identity primary key,
  content text not null
);

insert into notes (title,content,description) values
('english_pronunciation','wtffshlsdfhlghjd','Learning English');