import Head from "next/head";
export default function CustomAppHead() {
  return (
    <Head>
      <title>❄️ ❄️ ❄️ - 😿</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
