export default function Head() {
  return (
      <>
          <title>Welcome to Liansheng's blog </title>
          <meta name="description" content="Generated by create next app" />
      </>
  )
}
