export default function Head() {
  return (
      <>
          <title> 🗐 Liansheng Song</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </>
  )
}
